contact_links:
  - name: "Join Atri Community"
    url: https://join.slack.com/t/atricommunity/shared_invite/zt-1e756m1at-bZBxngvw7KWWO0riI4pc0w
    about: Join our community on Slack for other questions and general chat
